### ISSUE TITLE
Incorrect handling of tab indentation with rectangular selection 

### ISSUE THREAD

**Issue by schiffermtq** [asvetliakov/vscode-neovim#100]
Rectangular selections using Ctrl-V become non-rectangular, as tabs shift part of the selection:

![Screenshot_2019-12-17_13-00-59](https://user-images.githubusercontent.com/39995065/70993965-73b75280-20cd-11ea-9afb-aa84e7b1dccc.png)

**Comment by asvetliakov** [comment]
somehow related with ```tabstop``` setting

**Comment by asvetliakov** [comment]
well i don't think it's fixable. setting `tabstop` to 8 (or to some other value) makes HL incorrect since it counts tab width as displayable characters (while in vscode it's 1).
Setting `tabstop` to 1 (which i'm currently doing) corrects HL position but internally makes tabs in vim as 1width characters, this is why `<C-v>` is broken.

@justinmk FYI, any ideas here? ideally we need a character aware API

Currently best solution is to use spaces
