### ISSUE TITLE
cursor jumping around in visual mode

### ISSUE THREAD

**Issue by Coelancanth** [asvetliakov/vscode-neovim#129]
![1](https://user-images.githubusercontent.com/28604443/71561886-01575280-2a7d-11ea-84ac-b3b4119f4782.gif)

I only kept pressing "h" then "l", but unfortunately the cursor jumping around without any pattern.

vscode 1.41.1 with some extensions enabled
nvim 0.4.3 with 0 plugins and empty init.vim
vscode-neovim 0.0.45
win10 1909

vscodevim's cursor moves without any problem.

**Comment by asvetliakov** [comment]
are you using wsl or explicitly set `extension.remoteKind` to `workspace` ? Does it happen always or sometimes?

**Comment by 3nuc** [comment]
The cursor jumps around if you hold H, J, K or L but I always thought this is only a visual stutter. Down the line, the selected line is correct. I don't use extension.remoteKind or wsl for neovim

**Comment by asvetliakov** [comment]
>The cursor jumps around if you hold H, J, K or L but I always thought this is only a visual stutter. Down the line, the selected line is correct. I don't use extension.remoteKind or wsl for neovim

This may happen if you run the extension & neovim through remote extension host due to 3 round-trip latency but shouldn't happen with the same host version.
the cursor pos for `hjkl` is controlled by neovim, so it looks like sometimes an older event comes out of the order.

**Comment by asvetliakov** [comment]
@3nuc @Coelancanth Can you try with `0.0.46` version? I think it should improve things a lot due to more performant msgpack lib in neovim client.

**Comment by asvetliakov** [comment]
I tried to measure latency between receiving the cursor update from neovim and just before updating the cursor in vscode and in my tests it wasn't more than 0.02ms. So i don't think there is a problem with extension, and probably some other vscode extension kicks in here, for example language server is calculating highlight ranges for the same identifier under the cursor.

Worth trying is to disable other extensions and try to see if the problem still exist. Also worth to try to enable or disable if enabled `Editor: Cursor Smooth Caret Animation`

**Comment by 3nuc** [comment]
@asvetliakov Just installed vscode-neovim 0.0.46 and the issue still persists, even with all extensions disabled.

![neovim jumping cursor](https://user-images.githubusercontent.com/5359825/71691286-35958080-2da7-11ea-9f3b-cc0877dbdf6e.gif)
Recoreded on vscode-neovim 0.0.46, vscode 1.41.1, nvim 0.4.3

Could you try bumping up your [keyboard key repeat speed](https://www.dummies.com/computers/pcs/set-your-keyboards-repeat-delay-and-repeat-rate/) and seeing if the issue becomes worse for you when you hold j or k? My key repeat speed is a bit higher.

**Comment by asvetliakov** [comment]
My RR is already max on windows
![image](https://user-images.githubusercontent.com/8881674/71691626-2e22a700-2da8-11ea-8f0c-fcff5365e3d2.png). I'll try to increase it beyond the panel limits and see what happens.

@3nuc Can you try to disable indent guides, line highlight and line numbers

also i'm not sure from where your line numbers are coming from, because `relative` setting in vscode displays absolute line number for the current line, not relative:
![image](https://user-images.githubusercontent.com/8881674/71692121-5232b800-2da9-11ea-920b-94fad19f0690.png)

**Comment by 3nuc** [comment]
Crap, I ran "Disable all extensions" but didn't reload the window so some extensions stayed enabled. You're right - once I disable extensions and reload window it's ok - holding J or K moves the cursor smoothly.

**Comment by asvetliakov** [comment]
I believe your issue is some laggy extension (well, it may be ok, but takes extension host cycles and combined with vim extension makes things very crappy) which renders line numbers in vscode gutter. Custom indent guide extension and anything which renders decorators/put things into vscode gutter very often (e.g. on each cursor move) also may cause this. Both line numbers/indent guides are supported in native vscode - use them instead.

**Comment by Coelancanth** [comment]
Hi, thank you very much, now it moves smoothly!
