### ISSUE TITLE
Normal mode latency

### ISSUE THREAD

**Issue by alexozer** [asvetliakov/vscode-neovim#140]
I find that there is a notable bump in input latency while navigating in normal mode as compared to that of the vscodevim extension. Is there any plan to address this?

**Comment by asvetliakov** [comment]
Check [readme section](https://github.com/asvetliakov/vscode-neovim#performance-problems) and #129

This issue is caused by some 3rd party plugin which renders decorators very often (like indent guides,  bracket HL extension, etc...)
Also may be caused if you're trying to use remote neovim (from WSL for example) by explicitly overriding `extensionKind` to `workspace`

**Comment by alexozer** [comment]
So I made a minimal vim config just for vscode-neovim with none of my normal vim plugins or other settings like so...

```vim
if exists('g:vscode')
  " Leader
  let mapleader = ","
  let maplocalleader = "\\"

  " Make Y behave like D and C, instead of like yy
  nnoremap Y y$

  " Much better use of H and L
  noremap H ^
  noremap L $

  " Allow using ; to access command mode in normal and visual mode
  noremap ; :
  noremap : ;

else
" ...
```

And now vscode-neovim seems to have comparable, if not better latency than vscodevim! So that was probably the issue. Thanks!

I would probably mention somewhere in the README under the performance section that Vim plugins/settings may cause _latency_ specifically, rather than just "performance problems (likely cursor jitter)".
