### ISSUE TITLE
Reselect visual does not work

### ISSUE THREAD

**Issue by kibs** [asvetliakov/vscode-neovim#141]
When selecting multiple lines and eg. indent them using > and the tries to reselect the selection with gv, it only selects the first line.

this is useful for the following mapping

vmap > >gv
vmap < <gv

**Comment by asvetliakov** [comment]
`gv` works normally usually, but not with your mapping. Curious

**Comment by asvetliakov** [comment]
This works:
```vim
function! s:indent(key)
        normal! gv
        exe 'normal! ' . a:key
        normal! gv
endfunction

vmap > :<C-u>call <SID>indent('>')<CR>
vmap < :<C-u>call <SID>indent('<')<CR>
```

**Comment by kibs** [comment]
Thanks!

**Comment by kibs** [comment]
Well, the workaround doesn't really works here, not sure what happens, if is run the commands one at a time manually it works, but running it via the function it doesn't work, maybe some kind of synk issue because the function call is fast

**Comment by asvetliakov** [comment]
>Well, the workaround doesn't really works here, not sure what happens, if is run the commands one at a time manually it works, but running it via the function it doesn't work, maybe some kind of synk issue because the function call is fast

Can you give an example how you're running it through a function? If you're using something like `normal >` inside a custom function try to use `vmap <silent> > ...` for mapping instead just `vmap`

**Comment by kibs** [comment]
I pasted the example exactly as you wrote it

**Comment by asvetliakov** [comment]
The problem with original issue that neovim sends two cursor move events, first after performing `>` it resets cursor to the beginning of the visual selection, then restores it by `gv` command

At the same time vscode receives selection change event after first cursor move and checks if we need to send cursor update to neovim. Due to race condition because both redraw handler/selection handler are processed independently and asynchronously it thinks that selection was changed from second cursor move to the first one, so it tells neovim to move cursor to the first line.
