### ISSUE TITLE
Issues with large files

### ISSUE THREAD

**Issue by borring** [asvetliakov/vscode-neovim#153]
1. Open a new file
2. enter a gibberish first line, then `yy210p` to duplicate it
3. `G` to get to the bottom of the file.

What ends up happening:
The cursor stops at `line: 201`. Pressing `k` updates vscode to show the cursor near the end of the file.

Hang at >>200 lines
1. Open a new file
2. enter gibberish first line, then `yy800p` to duplicate it
3. `G` to get to bottom. (VSCode correctly jumps to bottom of file)
4. Use `kj` to move the cursor up and down once.
5. Use `gg` to get to the top

What ends up happening:
Hangs.

**Comment by asvetliakov** [comment]
First case is OK for me (Try with empty init.vim)

Reproduced second case

**Comment by asvetliakov** [comment]
Release `v0.0.50` with the fix

**Comment by borring** [comment]
Quick work! Btw, the first scenario was caused by this aesthetic setting

```
set cursorline
```
Workaround was to just `set nocursorline` if vscode is detected

**Comment by lacostenycoder** [comment]
I'm having this problem now making this extension unusable. 
NVIM v0.4.3
VSCODE Version: 1.45.0
MacOS Version: 10.14.6 (18G103)

Steps to reproduce: Open any file > 200 lines.
do SHIFT + G
file stops and line 201

Expected behavior: go to the bottom of the file.
I have no idea how or why this stopped working was working yesterday.

**Comment by uladkasach** [comment]
I too am still having this problem:
VSCODE-NEOVIM: v0.0.82
NVIM: v0.4.4
VSCODE: v1.57.1
UBUNTU: 21.04 (PopOs actually, but thats primarily just a ui difference)

Same steps to reproduce as posted above.
