### ISSUE TITLE
I would like to help :)

### ISSUE THREAD

**Issue by rajibahmed** [asvetliakov/vscode-neovim#177]
Hello,

I am a neovim user for awhile. I enjoyed the plugin myself, would love to offer support to improve this plugin. 

Let me know you thoughts.

**Comment by asvetliakov** [comment]
Contributions are always welcome! For starting, #178 is good candidate, also #166 , #147, #135 , #108 , #103 (although it's tricky because the clipboard could have 3 modes (e.g. characterwise, linewise, blockwise))

Also cleaning/refactoring of `controller.ts` is also welcomed (it's some kind of messy now) - for e.g. moving common stuff to helpers/utils
