### ISSUE TITLE
Close tab with ctrl+w c

### ISSUE THREAD

**Issue by trkoch** [asvetliakov/vscode-neovim#178]
This would be a nice complement to existing `ctrl+s` and `ctrl+c`.

_This extension is already doing a very impressive job. Thank you so much!_

**Comment by asvetliakov** [comment]
Contributions welcome if i won't do this next days, there could be some troubles because `<C-c>` isn't being sent to neovim and intercepted by vscode. However configuring `Ctrl+w Ctrl+c` as separate keybinding in `package.json` should help in this case. Once the keystroke is being sent to neovim it should be trivial to bind it and call vscode command to close active tab [here](https://github.com/asvetliakov/vscode-neovim/blob/87314441e3aba082577d811b229c3ffaa97d2150/vim/vscode-window-commands.vim#L85)

**Comment by trkoch** [comment]
I guess it was already implemented, but a typo slipped through? See https://github.com/asvetliakov/vscode-neovim/pull/180.

**Comment by asvetliakov** [comment]
Yes, mistype. But didn't you ask about `<C-w> <C-c>` ( the PR fixes `<C-w> c` )? (just checked neovim docs - `<C-w> <C-c>` cancels the command, so you had probably mean `<C-w> c`)

**Comment by trkoch** [comment]
I meant asking for `<C-w> c` but did in fact write `<C-w> <C-c>` 😀

**Comment by asvetliakov** [comment]
Oh yes, then fixed. Thank you!
