### ISSUE TITLE
Desync after exiting insert mode

### ISSUE THREAD

**Issue by sid-6581** [asvetliakov/vscode-neovim#186]
I just tried using this extension for the first time, but ran into some issues immediately. I'm on the latest version of VS Code on Windows 10, and the latest nightly build of neovim for Windows. I added the path to nvim, and didn't configure anything else.

The first thing I tried was entering insert mode, entering some characters, then exiting insert mode. The problem I immediately noticed was that for a second or two after exiting insert mode, VS Code would take over and accept input, and anything I typed would be inserted into VS Code's buffer. Then when normal mode kicks in, it's operating off what I inserted in insert mode. Any characters VS Code accepted and inserted into its buffer, vscode-neovim doesn't seem to know about. I can't put my cursor over them at all.

This doesn't seem like expected behavior on a pretty vanilla setup, so I'm curious what is going on.

**Comment by trkoch** [comment]
@sid-6581 You mention your setup is vanilla. Have you tried to disable _all_ extensions/plugins both in Neovim and VSCode? Especially plugins in Neovim modifiying the buffer/gutter mess around a lot.

**Comment by sid-6581** [comment]
I don't use any plugins in neovim/vim, but I did narrow down the problem to my init.vim. It's pretty simple with just some settings changes and mappings, but these lines ended up causing the problem:

![image](https://user-images.githubusercontent.com/28602336/74550011-409b0f00-4f16-11ea-834a-92fd787e54cb.png)

Once I comment out those lines, everything seems to stay in sync. It's easy enough to skip these lines for this plugin, but I'm curious what about them would cause this.

**Comment by trkoch** [comment]
@asvetliakov These kind of issues seem to pop-up often. Perhaps vscode-neovim should not use `.vimrc` by default and instead motivate users to include settings on a as-needed basis, be that by completely separate configuration or existing configuration with `exists('g:vscode')` checks.

**Comment by asvetliakov** [comment]
@sid-6581 
The actual problem here with `<C-o>` comes from mapping - the extension doesn't expect that insert mode exit will be sent by neovim, so it doesn't sync vscode buffer, so neovim doesn't know about the changes yet and not able to navigate.

BTW these mappings shouldn't work by default - are you passing `<Left>/etc` to neovim through vscode `keybindings.json` ? Only one exception here - is the macro recording mode

@trkoch
Similar issue may occur for #181 if you'll try to do `<C-o>k` - it won't know about the changes yet.

I'm not sure yet should the extension read init.vim or not by default. Let me think about that

**Comment by theol0403** [comment]
I'm going to close this, as it is just from a config issue, and may also be fixed by #585.
