### ISSUE TITLE
Copy paste in visual mode

### ISSUE THREAD

**Issue by pieterdd** [asvetliakov/vscode-neovim#194]
Suppose I made a selection in visual mode and I now want to access clipboard features. I noticed that CTRL+C doesn't work. What _can_ I do to copy the selection to the system clipboard? Do I have to copy through the command palette every time or is there a better way?

**Comment by poul1x** [comment]
<Shift-plus><y> works for me

**Comment by justinmk** [comment]
"+y

Just like in vim. This is a vim plugin, so it works the same as in vim. ctrl-c is cancel in vim.

**Comment by asvetliakov** [comment]
Unbinding `<C-c>` would also work

**Comment by pieterdd** [comment]
Fair enough, thanks for the tips!

**Comment by shividhar** [comment]
> Unbinding `<C-c>` would also work

Could you please give instructions on how to unbind the keys?

**Comment by dharmaturtle** [comment]
Since `<C-c>` is a default mapping, [you can't unmap it](https://unix.stackexchange.com/questions/180926/disable-or-remove-default-vim-keybinding). The command `imap <C-c> <Nop>` works as expected in the terminal (meaning CtrlC now does nothing), but it _keeps_ its "canceling" behavior in VS Code. Not sure how to make it stop.

**Comment by dharmaturtle** [comment]
Ah. [This issue](https://github.com/asvetliakov/vscode-neovim/issues/440) made it clear what the problem was.
