### ISSUE TITLE
Cursor position unreliable with wordwrap on

### ISSUE THREAD

**Issue by haberdashPI** [asvetliakov/vscode-neovim#204]
In LaTeX files I typically use a single line per paragraph, and apply appropriate wordwrap settings. This leads to very long lines (e.g. more than a full screen in length). This seems to generate unreliable behavior with vscode-neovim; the cursor position jumps around in unpredictable ways, and the display of highlights does not make sense: e.g. using vim-sneak, the highlighted jump positions are non-sensical. 

It seems that the position vscode-neovim thinks the text is at, is not actually where the text is.

**Comment by asvetliakov** [comment]
it's not possible to set correct neovim viewport size since vscode lacks required api, thus wordwrap is explicitly disabled by default and neovim viewport set to fixed value 500. In latest (non-released version) i increased it to 1000 and made it configurable, but it only masks the problem.
Also see #187 

Any overriding `set nowrap` settings will mess the things.

HL/visual mode outside of this range will work incorrectly because real neovim viewport is being scrolled but it doesn't notify about that remote clients.

`vim-sneak` is not supported as any plugin which works through `conceallevel` and won't be since there is no analogue of this in vscode. use easymotion fork

**Comment by haberdashPI** [comment]
Hi @asvetliakov; thank you for the prompt explanation. It's unfortunate this isn't supported by vscode. I love the idea of this package and was really excited by it, but for my purposes I will probably have to stick to using VSCodeVim (which can handle wordwrap); or maybe I'll just stop using a soft word wrap for my next LaTeX project...

**Comment by asvetliakov** [comment]
You can try to play with neovim width setting in next extension version. Once it'll be set to some high value (e.g. the longest line + some margin) it should work fine i think (with neovim word wrapping off, vscode word wrapping on)
