### ISSUE TITLE
Enable navigation inside jupyter cells

### ISSUE THREAD

**Issue by nkoep** [asvetliakov/vscode-neovim#210]
I was wondering whether there was a straightforward way to allow for navigation in normal mode inside jupyter code cells as provided by https://github.com/Microsoft/vscode-python? Right now, j and k only move the selection between cells.

**Comment by asvetliakov** [comment]
Can you try latest version. There was some work done here to support non text editors

**Comment by theol0403** [comment]
I just tried, and all text is input literally into the cells, there is no normal mode and only insert mode.
I think this is due to the notebook being rendered as a webview, so maybe this issue can be generalized to neovim inside text-input boxes in webviews.

However, if possible, enabling this feature would be awesome!
Google Collab is the only non-vim jupyter editor that supports vim shortcuts, and it does not support custom init.vim. Bringing neovim to vscode's jupyter editor would be amazing.

**Comment by asvetliakov** [comment]
If these cells are not visible as vscode editors then perhaps we can't do much here, unfortunately

**Comment by brdvlps** [comment]
Looks like this won't be supported in the vscode-jupyter plugin: microsoft/vscode-jupyter#1650

I will instead use the Python Interactive feature for my notebooks as [described here](https://code.visualstudio.com/docs/python/jupyter-support-py), since you have a regular editor window there.

**Comment by jwpeddle** [comment]
I'm using vscode version `1.58.0-insider` and this appears to _just work_ for me. One gotcha is that you won't be able to press escape to exit the cells, since this plugin catches Escape. I've worked around this by mapping a double-tap to explicitly exit cell editing.
```
nmap <Esc><Esc> <Cmd>call VSCodeNotify('notebook.cell.quitEdit')<CR>
```

**Comment by pokey** [comment]
Fwiw I removed all neovim `esc` mappings and trained my fingers to use `<Ctrl-C>` instead, because there are lots of situations in VSCode where the built-in `esc` behaviour is nice to have

**Comment by theol0403** [comment]
@pokey Could you give a list of situations where built-in `esc` is desired? If they are common enough usecases, I could add them to https://github.com/asvetliakov/vscode-neovim/blob/1be954ebf1329f0e4937418c24ebec93da02025f/package.json#L552

**Comment by pokey** [comment]
> @pokey Could you give a list of situations where built-in `esc` is desired? If there are common enough usecases, I could add them to
> 
> https://github.com/asvetliakov/vscode-neovim/blob/1be954ebf1329f0e4937418c24ebec93da02025f/package.json#L552

Might be out of scope for this issue, but here are a few that I ran into:
- When you're viewing an error on a line
- When you're viewing git diff for a line
- When there are message boxes in the bottom right

**Comment by kwsp** [comment]
I've come across this many times but haven't been able to find a solution to my problems: 

1. How do I navigate between cells in normal mode within a cell?
2. After executing a cell, I end up in the "vim" mode of the notebook where I can use `j` and `k` to move between cells. How do I enter a cell from here?

Thanks 😄

**Comment by userrand** [comment]
> I've come across this many times but haven't been able to find a solution to my problems:
> 
> 1. How do I navigate between cells in normal mode within a cell?
> 2. After executing a cell, I end up in the "vim" mode of the notebook where I can use `j` and `k` to move between cells. How do I enter a cell from here?
> 
> Thanks 😄

Maybe you already found a solution but, and I am not sure if this was from a configuration that I did in the past, for me pressing enter works for entering a cell. For navigating between cells, you have 2 options:

- I do not remember if I set this up in the past but pressing escape when in normal mode moves me to a sort of cell navigation mode where I can move between cells. I can then press enter from there to enter a cell.

- You can set keybindings to move directly to an adjacent cell when the cursor is at the boundary of a cell using the vscode "when context" option when defining keyboard shortcuts. Depending on the plugins you use, that might cause an issue where something like pressing an easymotion key followed by j would move to the cell below if the cursor is at the bottom instead of searching for characters with j. That is a separate question which, for the sake of brevity, I will not address unless asked. **Assuming you do not use easymotion like plugins**, you can maybe add the following to your keybindings.json (to find it you can use ctrl+shift+p then search for something like keyboard json)  where I think I got the when context from the keyboard shortcuts search UI (not the keybindings.json) by searching for downarrow and then looking at the "Notebook: Focus Next Cell Editor" entry then adding the neovim normal mode constraint I saw in other neovim keyboard shortcuts.

**Note**: Code below was adapted from a non-qwerty keyboard layout, but I do not think that matters

```
{
        "key": "j",
        "command": "notebook.focusNextEditor",
        "when": "config.notebook.navigation.allowNavigateToSurroundingCells && editorTextFocus && inputFocus && notebookEditorFocused && !accessibilityModeEnabled && !isEmbeddedDiffEditor && notebookEditorCursorAtBoundary != 'none' && notebookEditorCursorAtBoundary != 'top' && editorTextFocus && neovim.init && neovim.mode == 'normal' "
    },
{
        "key": "a",
        "command": "notebook.focusPreviousEditor",
        "when": "config.notebook.navigation.allowNavigateToSurroundingCells && editorTextFocus && inputFocus && notebookEditorFocused && !accessibilityModeEnabled && !isEmbeddedDiffEditor && notebookEditorCursorAtBoundary != 'bottom' && notebookEditorCursorAtBoundary != 'none' && editorTextFocus && neovim.init && neovim.mode == 'normal' "
    }
```
