### ISSUE TITLE
Remote Extension: Does not work with SSH (OSX -> Ubuntu)

### ISSUE THREAD

**Issue by christo-ph** [asvetliakov/vscode-neovim#225]
Running Visual Studio Code on OSX.

Development env on remote Ubuntu.

Settings for User and Remote[SSH: ubuntu] done.

1. Local (User) to local nvim and init.vim -> works
1. Remote (SSH: Ubuntu) to remote nvim and remote init.vim -> does not work
1. Remote without any settings -> does not work

I am unable to insert anything to the editor. Also `:` or `/` do not seem to do anything.

**Comment by asvetliakov** [comment]
I don't have any plans to support remote neovim. Perhaps it's possible to force extension to be installed remotely through VSCode and use remote extension host, but you'll be anyway disappointed for lag & slowness

**Comment by hgezim** [comment]
Porting those (vim) settings from machine to machine instead of keeping them on remote host is quite unfortunate :(

**Comment by theol0403** [comment]
Maybe #668 can help, but I know it's not exactly what you are looking for. I don't think there is a good solution for using remote nvim instance, nor would it work very well (latency).

**Comment by still-dreaming-1** [comment]
I want this so badly. It would be the killer app of both VS Code and Neovim. The way Remote Extension works is so much better than anything similar other IDEs support. I can't seem to configure language servers properly in Neovim, but it works great in VS Code. But I can't just use VS Code without Neovim, that would be nuts. I'm so used to just sshing into a machine and using Neovim from there, and so this would be a great way to effectively do the same thing from VS Code. I'm confused, the reason you don't want to support it is because you are concerned it will be slow? Whenever I use VS Code with the Remote Extension it is not slow normally, so why would it all of a sudden become slow just because the server side is communicating a Neovim running on that same server?

**Comment by theol0403** [comment]
I think this is alright possible with https://github.com/vscode-neovim/vscode-neovim/pull/1000

**Comment by still-dreaming-1** [comment]
> I think this is already possible with #1000

So it's just waiting for someone to review and merge it, since Aug 10, 2022?
