### ISSUE TITLE
Cursor position error

### ISSUE THREAD

**Issue by Reasuon** [asvetliakov/vscode-neovim#284]
When the cursor position I selected exceeds the 100th line of the text, my cursor position will be automatically bounced back, but the operation is still performed at the selected position, as shown in the GIF

nvim version: 0.4.2 & 0.5.0 (Will always be like this)
Neo Vim(vscode plugin) version: 0.0.50
vscode version: 1.46.0

![CursorError](https://user-images.githubusercontent.com/38161433/84475653-82b74000-acbf-11ea-87d4-90574bdcc663.gif)

**Comment by jhonasiv** [comment]
I was having this same error. What worked for me was disabling the vim-gitgutter plugin in my init.vim. I just tried this, so I'm not sure if it will keep working. Maybe it is a conflict between gitgutter and another extension on vscode.

**Comment by lgsmith** [comment]
I've been having similar issues just editing some C++ source, and I don't have that plugin in init.vim or my .vimrc. I'm really new to using neovim and this plugin instead of the vim-emulation plugin, but it's been driving me nuts.

When I double click on a variable name to highlight it now it bounces my cursor to the end of the file. Dragging and clicking also has some probability to do insane things. And although I've remapped k and j to gk and gj, sometimes it doesn't step down to the same col in the next softwrapped line. It translates over a bit, as though it's not actually getting the correct softwraping (I don't use softwrapping with code, but I do with editing .tex files).

If someone thinks I'm having a different issue I'm happy to make a separate ticket. Otherwise...bump?

**Comment by Reasuon** [comment]
> I was having this same error. What worked for me was disabling the vim-gitgutter plugin in my init.vim. I just tried this, so I'm not sure if it will keep working. Maybe it is a conflict between gitgutter and another extension on vscode.

Thank you for your reply, it is very effective for the problem I encountered, I have solved it according to your reply, thanks again

**Comment by Reasuon** [comment]
> I've been having similar issues just editing some C++ source, and I don't have that plugin in init.vim or my .vimrc. I'm really new to using neovim and this plugin instead of the vim-emulation plugin, but it's been driving me nuts.
> 
> When I double click on a variable name to highlight it now it bounces my cursor to the end of the file. Dragging and clicking also has some probability to do insane things. And although I've remapped k and j to gk and gj, sometimes it doesn't step down to the same col in the next softwrapped line. It translates over a bit, as though it's not actually getting the correct softwraping (I don't use softwrapping with code, but I do with editing .tex files).
> 
> If someone thinks I'm having a different issue I'm happy to make a separate ticket. Otherwise...bump?

I suggest you open a new issues, or try to delete all the plugins, and try to see if the problem will still occur. If not, then install all the plugins back until you find the problem
