### ISSUE TITLE
Search and Replace does not work with angle brackets

### ISSUE THREAD

**Issue by borring** [asvetliakov/vscode-neovim#300]
Consider the text and command:
```
<xml>
```
`s/\v\<xml/<lmx/`

We should expect that the text is changed from xml to lmx.

What actually happens: entire match is deleted as if the replacement pattern was empty.

Neo Vim plugin: 0.0.50
Neovim: 0.4.2
OS: Windows

**Comment by colinxs** [comment]
No a contributor, but shouldn't the command be `s/\<xml/<lmx/`?

That works in both vscode-neovim and neovim from the terminal.

**Comment by borring** [comment]
For me, that just turns
`<xml>` into `<>`

**Comment by colinxs** [comment]
So I was incorrect and your original command `s/\v\<xml/<lmx/` is correct.  `s/\v\<xml/<lmx/` correctly changes `<xml>` to `<lmx>` in the terminal with neovim 0.4.3 and 0.5.

**Comment by colinxs** [comment]
I looked into this a bit more and think I fixed it.

1. `s/\v\<xml/<lmx/` results in `>` i.e. it deletes the query as @borring pointed out, but `s/\v\<xml/foo/` works correctly and yields `foo>`. So the issue is with the replacement. Using the query `\v\<xml` in forward/reverse search also does the right thing.
2. The call to `normalizeString` [here](https://github.com/asvetliakov/vscode-neovim/blob/54e46eac62a9c537bad55073293763ff434982f1/src/controller.ts#L2333) doesn't appear to do the right thing. `normalizeString` is supposed to change `<` to `<LT>` (for some reason), but only replaces the first instance. According to the code I'd expect `keys` to be `<C-u>s/\v\<LT>xml/<LT>lmx/` but the actual value is `<C-u>s/\v\<LT>xml/<lmx/`.

I know nothing about TypeScript or NeoVIM's protocol, but changing its definition to:
```ts
    private normalizeString(str: string): string {
        // Old definition: return str.replace("\n", "<CR>").replace("<", "<LT>");
        return str.replace(/\</g, "<LT>").replace(/\n/g, "<CR>");
    }
```
appears to fix things. I guess `String.replace` only replaces the first match if given a `String` and must be passed a `RegExp` with the `g` modifier to replace all matches.

@asvetliakov want to take a look at this?

I don't like TypeScript.
