### ISSUE TITLE
Cursor does not stay in position after exiting insert mode

### ISSUE THREAD

**Issue by kpeters-cbsi** [asvetliakov/vscode-neovim#321]
Observed behavior: When I add text in insert mode (i.e. hit "i", type some text) and then hit Escape to get out of insert mode, the cursor goes to the top of the class (when editing a class in Typescript and the previous cursor position is inside the class definition) or the top of the document. When editing a JSON, Markdown, or plain text file, the cursor returns to the top of the document. 
Expected behavior: The cursor stays at its current position after hitting "Escape".

Note that to reproduce this behavior, you have to insert some text. Just hitting "i" and then "Escape" doesn't do it.

**Comment by asvetliakov** [comment]
That's not correct behavior. Try with empty `init.vim`

**Comment by kpeters-cbsi** [comment]
That fixes it, which suggests that it's something in my `init.vim`, copied below:

```
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vim/vimrc
```
vimrc attached.
[vimrc.txt](https://github.com/asvetliakov/vscode-neovim/files/5119404/vimrc.txt)

**Comment by asvetliakov** [comment]
i'm not sure, but probably this block is culprit:

```
if has("autocmd")
	augroup MyResetCursor
	autocmd BufReadPost *
				\ if line("'\"") > 0 && line("'\"") <= line("$") |
				\   exe "normal! g`\"" |
				\ endif
	augroup END
endif
```

**Comment by kpeters-cbsi** [comment]
Yes, that seems to have been the culprit. I've had that in my .vimrc for a
long time before this started happening, though - what changed?

**Comment by asvetliakov** [comment]
Are you sure 100%? Because that seems neovim bug then - `BufReadPost` is triggered after calling `nvim_buf_set_lines` (which happens after you exit insert mode) which is wrong. You should report this to neovim repo, in meantime you can disable this (and few more things) for the extension with `exists('g:vscode')`

**Comment by kpeters-cbsi** [comment]
Yes, I'm 100% sure. It was fine as late as this past Friday.

**Comment by asvetliakov** [comment]
You mean you have been using this extension and it didn't happen previously? Ah, then it's related to `.` repeat operator work released these weekends - after exiting the insert mode, the extension creates empty buffer with window, replay changes here and closes it. That's why `BufReadPost` is being fired and your cursor is messed.

So that's not neovim problem then. Anyway, this block doesn't make sense with vscode, so feel free to wrap it with check above.

**Comment by ashchan** [comment]
Having the same issue from around the same time.

**Comment by asvetliakov** [comment]
@ashchan Investigate your init.vim for any cursor setting/resetting commands. Nothing i can do here and they don't make sense anyway - neovim sees any opened file as new scratch file. Any command restoring state won't work and harm.

Closing the issue since it's the configuration issue

**Comment by ashchan** [comment]
@asvetliakov Thanks. Just checked my vimrc and found the same configuration.
