### ISSUE TITLE
:w, :q ... commands are not working

### ISSUE THREAD

**Issue by jjangun** [asvetliakov/vscode-neovim#35]
Hello, 
First of, all thank you for developing a great extension.
As you know :w, :q ... are not working.

**Comment by asvetliakov** [comment]
window/buffer management should be performed by vscode by design. At some time, i'll rebound ```:w```, ```:q``` etc to perform vscode commands, but i have more important issues to do right now.

If it bothers you much right now, you can use something like [cmdalias](https://github.com/vim-scripts/cmdalias.vim) and bind ```:w``` to ```call VSCodeCall("workbench.action.files.save")``` and similar command in your init.vim
