### ISSUE TITLE
Support current Neovim release

### ISSUE THREAD

**Issue by pedrominicz** [asvetliakov/vscode-neovim#353]
Support the latest _release_ of Neovim. Not even Archlinux is on 0.5.0. I don't see what big change could make it worth while to inconvenience users to manually install a nightly build.

An okay compromise would be instructing users how to downgrade the extension to work with current Neovim.

**Comment by asvetliakov** [comment]
>An okay compromise would be instructing users how to downgrade the extension to work with current Neovim.

![image](https://user-images.githubusercontent.com/8881674/92426646-c8828800-f18a-11ea-9d97-9eeb8a0209c7.png)

`0.0.52` is the latest version which works with neovim 0.4

I can't support neovim 0.4 anymore because cursor positioning worked through clunky workaround previously - it was using `set number` to render line numbers in neovim do determine current real cursor position in a buffer based on string in the gutter. Yeah, funny, and error prone. Thankfully, neovim devs implemented correct ui event but it's available in 0.5 nightly only.

You don't need to have neovim 0.5 installed system wide. You can drop off the tarball into some directory and just use it for vscode, while continue to use 0.4 from your package manager for your daily non-vscode needs.

**Comment by AprilArcus** [comment]
You should have waited to ship improved cursor positioning until 0.5 was released.

**Comment by asvetliakov** [comment]
The previous method was the big headache, so i'd say `working cursor` instead of `improved`. I don't see a big problem dropping a tarball of neovim nightly or running `brew install neovim --HEAD`. [But i see a big headache of trying to keep old way](https://github.com/asvetliakov/vscode-neovim/issues?q=is%3Aissue+is%3Aclosed+cursor).

Anyway, this is free OSS software, so if you would like to work on PR which will restore old cursor behavior for 0.4 (either under configuration flag or by neovim version checking)  - i'd be happy to review and accept it.

**Comment by pedrominicz** [comment]
From a developer point of view I 100% understand you. Reading about the cursor problem made me empathize with your decision. However, from the user point of view the plugin just randomly started warning about an update then broke. Installing from a tarball isn't hard, but isn't ideal for user satisfaction (I guess most people find it pretty annoying).

A few suggestions I have:
- Add documentation about installing an older version to the README
- Add a warning to the newest version like "you can install a newer Neovim _or_ downgrade the plugin"
- Make sure people who have downgraded get some sort of notification when Neovim 0.5 gets pushed to, say, Ubuntu's repos (I guess when Ubuntu have it most other distros will)

**Comment by JoeSchr** [comment]
I love it! Now I finally can work with 2 panes next to another and also editing in diff view works! Keep pushing the envelope!

**Comment by hholst80** [comment]
I'm using vscode-nightly on 4 different machines so I have to do this four times. But the end result is worth it. Keep up the great work!

**Comment by exapsy** [comment]
I believe it's still not great idea from a user's experience standpoint to use it on the stable version of the plugin.

I know I'm overanalyzing, but this is what happens from a user's standpoint

1. User installs VSCode neovim plugin (yay! Happy)
2. User sees he can't use the plugin with his neovim's version
3. User now tries to update neovim, because he thinks 0.5+ are stable versions
4. User sees that they cant do that, so maybe the package manager is not updated yet? They have to search for that
5. Oh, apparently, it's not yet stable version. So now they search for this in vscode-neovim's git issues (gets here)
6. Finds out he can use a previous version which didn't use neovim 0.5+

Like, a lot of friction is created because of this. This could have been made as a beta version or something.

**Or, at least provide the required information, like a link that leads here or anything that helps in the error dialog, to reduce the friction.**

**Comment by catofnineswords** [comment]
This would be great, but the nightly builds of neovim started failing as of a few weeks ago.  (See their travis build issue thread)
This is the problem that gets passed on to users when an application depends on non-released and unstable upstreams.

**Comment by 3nuc** [comment]
https://github.com/neovim/neovim/issues/13312#issuecomment-753643798 Ubuntu unstable PPA is back up again

The appimage/tarball releases are back also

**Comment by 3nuc** [comment]
https://github.com/neovim/neovim/issues/13312#issuecomment-753643798 Ubuntu unstable PPA is back up again

The appimage/tarball releases are back also

**Comment by trkoch** [comment]
Are nightlies archived? Perhaps @asvetliakov could link to a known working version for the time being.

**Comment by schiegl** [comment]
It would be helpful to know which exact version you tested this extension with. Because I'm having problems with the cursor getting out of sync with neovim or `o` inserting a newline correctly.

**Comment by Shatur95** [comment]
@schiegl, I also experience desync sometimes, especially when my cpu is heavily loaded. This is just an issue of the extension.

**Comment by schiegl** [comment]
@Shatur95 I see. For me it has nothing to do with cpu load. It happens each time I use it. Which makes this extension unfortunately unusable for me.

**Comment by samvv** [comment]
One solution would be to ship a precompiled binary of Neovim with this extension. That way, you always have a working version of a release that is guaranteed to work. I would like to look into it, but first I need to make sure I can make the unit tests pass locally. 😅

**Comment by joemsak** [comment]
Just throwing it out there that in my experience on Debian with Windows WSL2 ... this is the latest version I can get on apt

```neovim is already the newest version (0.3.4-3).```

So I can't even get 0.4 apparently?

**Comment by 3nuc** [comment]
@joemsak register this ppa: https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable

then sudo apt install neovim again. After that it should be 0.5

**Comment by joemsak** [comment]
Thank you @3nuc I really appreciate your help, however, I get this error:

```
E: The repository 'http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu impish Release' does not have a Release file.                                                                                                              
N: Updating from such a repository can't be done securely, and is therefore disabled by default. 
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I took a look at the manpage but am not confident about what I should do (not a total linux expert especially around this sort of thing)

**Comment by 3nuc** [comment]
>E: The repository 'http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu **impish** Release' does not have a Release file.                                                                                                              

You're on Ubuntu 21.10 (the unstable cutting edge version), whose codename is Impish Indri (hence `impish` in the above error).

Neovim probably doesn't publish binaries for such a new version, so you can try installing the ppa for a past release eg. `focal` (instead of `impish`)
https://askubuntu.com/questions/293203/how-can-i-add-a-ppa-from-a-previous-release

**Comment by joemsak** [comment]
Is Debian the same thing as Ubuntu 21.10? I'm confused
