### ISSUE TITLE
Cursor resetting in insert mode for workspaces with python files

### ISSUE THREAD

**Issue by daniel-bray** [asvetliakov/vscode-neovim#562]
The cursor resets itself to the originally inserted position after a couple of seconds in insert mode. I have all other extensions disabled. 

![neovimpython](https://i.makeagif.com/media/3-01-2021/KP2gQz.gif)

**Comment by daniel-bray** [comment]
Issue must have been with my nvim settings. Resetting them fixed the problem.

**Comment by MarWeUMR** [comment]
Since this morning I'm having the exact same issue. I've made a small .gif to showcase the behaviour:

![jump](https://user-images.githubusercontent.com/27370794/111773518-9165ff80-88ae-11eb-90f3-4164ebba05c6.gif)

The weird thing is, it just started out of the blue and now is present in every vscode instance. 
Even using a portable vscode version without any other extensions and a different neovim installation the issue is triggered as soon, as a python file is opened.
