### ISSUE TITLE
Unable to bind <C-k> from init.vim

### ISSUE THREAD

**Issue by shth** [asvetliakov/vscode-neovim#614]
my init.vim looks like this
```
if exists('g:vscode')
  noremap <C-h> :call VSCodeNotify("workbench.action.navigateLeft")<CR>
  noremap <C-l> :call VSCodeNotify("workbench.action.navigateRight")<CR>
  noremap <C-k> :call VSCodeNotify("workbench.action.navigateUp")<CR>
  noremap <C-j> :call VSCodeNotify("workbench.action.navigateDown")<CR>
else
...
```

The thing I want to do is to use <C-h/j/k/l> to navigate windows in vscode. All the binding works except for \<C-k\> . I get this message from vscode instead
![Screenshot 2021-04-23 123355](https://user-images.githubusercontent.com/15711961/115818884-549ea280-a430-11eb-96c8-c0ca1e8e807a.png)

What have I done wrong? Or should I just unbind all the ctrl+k bindings from vscode? Thanks.

**Comment by JoshTRN** [comment]
You don't need to do that. The neovim key bindings only send it when the text editor is in focus. Add this custom key binding to your `keybindings.json` 

```
	{
		"key": "ctrl+k",
		"command": "workbench.action.navigateUp",
		"when": "terminalFocus"
	},
```

**Comment by theol0403** [comment]
VSCode uses ctrl-k for a ton of default keybindings, which is why it's not possible to remap. This is because even if the C-k were sent to neovim (which it isn't), vscode would be waiting to know for sure that you didn't mean to use one of the default chorded bindings (like C-k C-s to open keybindings). The only solution is to unmap all vscode default bindings, which would be tedious.

However, like Josh said, you don't need to send it to neovim, you can bind it directly in VSCode. The problem would still be there though. A solution might be to use Alt or a different letter.
