### ISSUE TITLE
`:e`, `:split`, `:vsplit`, and `:tabe` with local file argument don't open file

### ISSUE THREAD

**Issue by ZackPlauche** [asvetliakov/vscode-neovim#675]
Using latest version of vscode, Neovim, and this extension on Windows.

When using the `:e` or other file opening commands, I'm unable to just type a file in the current directory and open it.

It goes like this:
1. I type `:e myfile.txt`
2. Nothing happens

They do work with directories like $MYVIMRC or full paths like "C:/Users/username/...".

The only way I'm able to work with local files is if I just press `:e` then press enter, THEN search for the file in the drop-down menu.

I want to just type out `:e ` with the filename in one line  to quickly edit the file like in regular Vim or Neovim (which, the suggestions of files on the local directory do pop up, but even if I click on them NOTHING happens).

**Comment by theol0403** [comment]
I can confirm on linux as well. I think this might be the same as 663.

**Comment by BrianZhang1** [comment]
> I can confirm on linux as well. I think this might be the same as #663.
> 
> $MYVIMRC works for me, but any relative files do not.

For me, `:e $MYVIMRC` doesn't work but using :e (file path) works as long as the file path starts from root ~. If it doesn't start with ~ it doesn't work for me. 

Also the autocomplete on the directory name is broken too, instead of appending a directory to the current path it deletes the entire path and just puts :e directory.

Example:
`:e ~/some/directory`
Then autocomplete the directory `project`, it becomes
`:e project`
When it should be
`:e ~/some/directory/project`

It seems the :e function is kinda just incomplete.

**Comment by ZackPlauche** [comment]
> > I can confirm on linux as well. I think this might be the same as #663.
> > $MYVIMRC works for me, but any relative files do not.
> 
> For me, `:e $MYVIMRC` doesn't work but using :e (file path) works as long as the file path starts from root ~. If it doesn't start with ~ it doesn't work for me.
> 
> Also the autocomplete on the directory name is broken too, instead of appending a directory to the current path it deletes the entire path and just puts :e directory.
> 
> Example:
> `:e ~/some/directory`
> Then autocomplete the directory `project`, it becomes
> `:e project`
> When it should be
> `:e ~/some/directory/project`
> 
> It seems the :e function is kinda just incomplete.

I can confirm this behavior as well.
