### ISSUE TITLE
My init.vim has no effect on vscode

### ISSUE THREAD

**Issue by ShadyZekry** [asvetliakov/vscode-neovim#789]
I have added simple lines to a test `init.vim` like 
```vim
nnoremap j zzj
nnoremap k zzk
```
Then added this line to my `settings.json`
```json
"vscode-neovim.neovimInitVimPaths.linux": "$HOME/.config/nvim/init.vim",
```
And nothing happens, and it looks like the file content has no effect on the editor, or it's not used.

<br>

## Sidenotes
- My `init.vim` is working fine on my nvim (on terminal)
- I think the extension is reading the file, because I have changed my `init.vim` path, and the extension outputs `E282: Cannot read from "$HOME/temp_file_init.vim"` through vscode notification bar .

**Comment by theol0403** [comment]
1. It's possible the `$HOME` placeholder isn't working - try specifying the exact path to your home directory (like `/home/user/.config/...`).
2. Its possible that your init.vim is actualy working, but that the `nnoremap j zzj` has no effect because of the way the plugin works. Try using `nmap` instead of `nnoremap`. 
3. Its possible that the mapping you are looking for isn't supported by the plugin. To achieve the same functionality, you should change vscode settings - there is likely one that will let you center the cursor.

**Comment by ShadyZekry** [comment]
I have just changed `nnoremap` to `nmap` and it works well now, thanks, @theol0403.
